

# ::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Receivers
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"


# ::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Processors
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::
processors:
  batch:


# ::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Exporters
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::
exporters:
  # Data sources: traces, metrics, logs
  file:
    path: /logs.json

  # Logging
  logging:
    loglevel: debug

  # Data sources: traces
  #otlp/jaeger:
  #  endpoint: jaeger:4317
  #  tls:
  #    insecure: false
  #    insecure_skip_verify: true



# ::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Extensions
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::
extensions:
  health_check:
  pprof:
  zpages:


# ::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Service
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file,logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file,logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file,logging]