services:
  collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./collector-edge/config/collector-edge-working.yaml:/etc/otelcol/config.yaml
      - ./collector-edge/logs/collector.json:/logs/collector.json
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    networks:
      - otel

networks:
  otel:
    driver: bridge
