receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:55681"
# Add other receivers as needed, e.g., Zipkin for compatibility with Jaeger
exporters:
  jaeger_elasticsearch:
    hosts:
      - http://elasticsearch:9200

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger_elasticsearch]